name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: dumb-flask-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name dumb-flask-app dumb-flask-app:latest
        sleep 5  # Give the container time to start

        # Test the ping endpoint
        RESPONSE=$(curl -s http://localhost:5000/ping/)
        echo "Ping response: $RESPONSE"

        if [[ $RESPONSE == *"\"status\":\"ok\""* ]]; then
          echo "Ping test passed!"
        else
          echo "Ping test failed!"
          exit 1
        fi

        # Test a sample request
        RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d '{"test":"data"}' http://localhost:5000/test)
        echo "Sample request response: $RESPONSE"

        if [[ $RESPONSE == *"\"message\":\"Request received and logged\""* ]]; then
          echo "Sample request test passed!"
        else
          echo "Sample request test failed!"
          exit 1
        fi

        docker stop dumb-flask-app
        docker rm dumb-flask-app

    - name: Login to Quay.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Push to Quay.io (Multi-architecture)
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: quay.io/haoliu/dumb-flask-app:latest
